name: Update gh-pages
on: 
  push:

jobs:
  gh-pages:
    name: Update gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          # npm run build
          node ghu build

      - name: Checkout contents
        uses: actions/checkout@v2
        with:
          path: 'gh-pages'
          ref: 'pages'

      - name: Prepare gh-pages
        run: |
          cd gh-pages
          git checkout --orphan gh-pages
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "Original"

      - name: Update
        run: |
          cd gh-pages
          echo "::group::Add pages"
          cp -avr ../build/* ./
          cp -avr ../404.html ./
          cp -avr ../_config.yml ./
          git add .
          git commit -m "Add: page"
          echo "::endgroup::"

      - name: Publish
        run: |
          cd gh-pages
          git push -f origin gh-pages
